### ISSUE TITLE
Issue - sometimes reports "unknown" instead of 0

### ISSUE THREAD

**Issue by i00** [robmarkcole/HASS-Deepstack-object#93] opened 2019-11-29 01:27 UTC
![image](https://user-images.githubusercontent.com/1435262/69837538-0b7a0b80-129b-11ea-90c7-532f8f352f98.png)

I quite often get this repose, when I move in front of the camera it changes to 1??

... sometimes reports 0 sometimes unknown when no people are in front of it!

**Comment by i00** [comment] 2019-11-29 08:51
The unknowns seem to increase if I check deepstack more regularly... for e.g if I use 1 second updates on several cameras at a time (all cameras are 6MP)

**Comment by robmarkcole** [comment] 2019-11-29 10:20
Probably deepstack is returning an error that is not being handled. I am waiting for an update to deepstack which will improve error handling

**Comment by shbatm** [comment] 2020-02-13 14:33
Does `self._dsobject.predictions` ever return a "falsy" result? If so, `self._state` may never get changed from `None` and would result in an `unknown` being shown in HASS.

**Comment by rbflurry** [comment] 2020-03-12 13:54
Changing    
https://github.com/robmarkcole/HASS-Deepstack-object/blob/master/custom_components/deepstack_object/image_processing.py#L267

to

` return "0" if self._state is None else self._state`

Worked for me on this.

**Comment by i00** [comment] 2020-03-12 22:35
Not a great solution ... you would be better not re-setting the _state to None IMHO ... otherwise it will keep flicking between 1 and 0 for instance ... but either way ... should prob work out why the try-catch is failing ... I will have a look at this when I have the time.

**Comment by robmarkcole** [comment] 2020-12-17 05:29
This is intended behaviour, if there has not been a scan by Deepstack, closing

**Closed by robmarkcole** 2020-12-17 05:29 UTC
